import type { DashboardPage } from '../types'

export const dashboardPages: DashboardPage[] = [
  {
    id: 'executive-overview',
    label: 'Executive Overview',
    heading: 'Executive Overview',
    subheading: 'Staða sönnunargagna, óvissa og brýn gagnabil',
    briefingSummary:
      'Yfirlit yfir fimm lykilniðurstöður með skýrum mörkum milli staðfestingar, sterkrar ályktunar og ósannaðrar orsakatúlkunar.',
    riskSignal:
      'Policy without measurement creates blind governance risk.',
    confidence: 'high',
    freshness: 'Apr 2026',
    evidenceLevel: 'confirmed',
    claims: [
      {
        id: 'exec-f1-text-silence',
        claim:
          'Textaeyða um atvinnuleysi/sjálfvirknivæðingu í stefnunni er tölvulega staðfest.',
        level: 'confirmed',
        state: 'verified',
        sourceLabel: 'README.md + scripts/02_verify_textanalysis.py',
        methodNote: 'Bein orðaleit á opinberri PDF útgáfu.',
        caveat: 'Lýsing á texta, ekki orsakaályktun.',
        lastVerified: '2026-04-11',
      },
      {
        id: 'exec-f2-pattern',
        claim:
          'ICT mynstur sýnir samhljóma merki tilfærslu, en orsakasamband er ósannað.',
        level: 'strong-inference',
        state: 'provisional',
        sourceLabel: 'VIN01110, JVS00001, FYR04101, THJ11011',
        methodNote: 'Samanburður tímaraða með tveimur baseline gluggum.',
        caveat: 'Vantar J62 tekjutölur fyrir 2025.',
        lastVerified: '2026-04-11',
      },
    ],
    modules: [
      {
        id: 'exec-status-ribbon',
        title: 'Findings Status Ribbon',
        subtitle: '5 findings mapped to evidence levels',
        sourceLabel: 'EPISTEMIC_CLAIMS.md',
        methodNote: 'Flokkun í confirmed / strong-inference / unproven.',
        caveat: 'ASÍ þinggögn ólesin að fullu.',
        state: 'verified',
        includesChart: false,
      },
      {
        id: 'exec-claims-matrix',
        title: 'Claims Matrix',
        subtitle: 'Staðfest, ályktun og ósannað aðskilið',
        sourceLabel: 'EPISTEMIC_CLAIMS.md',
        methodNote: 'Sýnir tvö mál: textamál og vinnumarkaðsmál.',
        caveat: 'Matrix er framsetning, ekki ný gögn.',
        state: 'verified',
        includesChart: true,
        chartKind: 'ranked-table',
        chartUsageIntent: 'Fljót yfirferð á stöðu fullyrðinga og sönnunarstigi.',
        chartFallbackNote: 'Sýnir töfluuppsetningu þar til gagnatenging er virk.',
        annotation: 'Mál A stendur þótt Mál B veikist.',
      },
      {
        id: 'exec-immediate-actions',
        title: 'Immediate Actions',
        subtitle: 'Þrjár brýnustu gagnaóskir',
        sourceLabel: 'MEMO_EMBATTISMANN.md',
        methodNote: 'Prioritering eftir policy impact.',
        caveat: 'Svarhlutfall stofnana óþekkt.',
        state: 'stale',
      },
    ],
    missingDataNote:
      'Vantar fulla ASÍ-ályktunarlestur og uppfærðar geiratekjur til að herða niðurstöðu 2.',
  },
  {
    id: 'ict-trifecta',
    label: 'ICT Trifecta',
    heading: 'ICT Trifecta',
    subheading: 'Tekjur, ráðningar, lausar stöður, framleiðni og atvinnuleysi í NACE J',
    briefingSummary:
      'Síðan sýnir samtímaþróun sem er samhljóða framleiðnitilfærslu, með skýrum fyrirvörum um orsakasönnun.',
    riskSignal:
      'Growth without hiring can mask structural transition risk.',
    confidence: 'medium',
    freshness: 'Apr 2026',
    evidenceLevel: 'strong-inference',
    claims: [
      {
        id: 'ict-triple-signal',
        claim:
          'Tekjur hækka á meðan ráðningar dragast saman og hlutfall lausra starfa fellur.',
        level: 'strong-inference',
        state: 'provisional',
        sourceLabel: 'FYR04101 + VIN01110 + JVS00001',
        methodNote: 'Tvær baseline stillingar (2019 og 2022).',
        caveat: 'Tekjur 2025 ekki að fullu birtar í sama flæði.',
        lastVerified: '2026-04-11',
      },
    ],
    modules: [
      {
        id: 'ict-series',
        title: 'Multi-signal Timeline',
        subtitle: 'Revenue, Employment, Vacancy Rate',
        sourceLabel: 'Hagstofa PxWeb',
        methodNote: 'Samræmd tímahvarfatafla fyrir þrjár víddir.',
        caveat: 'Samanburður krefst unit normalization.',
        state: 'provisional',
        includesChart: true,
        chartKind: 'line',
        chartUsageIntent: 'Samhliða trend fyrir tekjur, ráðningar og laus störf.',
        chartFallbackNote: 'Placeholder trend frame með samræmdum metadata svæðum.',
        includesComparisonToggle: true,
        annotation: 'Baseline switch: 2019 vs 2022.',
      },
      {
        id: 'ict-productivity',
        title: 'Labour Productivity Context',
        subtitle: 'THJ11011 narrative framing',
        sourceLabel: 'THJ11011',
        methodNote: 'Productivity sem samhengi við ráðningarmynstur.',
        caveat: 'Ekki bein orsakasönnun um AI áhrif.',
        state: 'provisional',
        includesChart: true,
        chartKind: 'area',
        chartUsageIntent: 'Samhengissvæði fyrir framleiðni og breytingarhraða.',
        chartFallbackNote: 'Area skeleton sem sýnir state + source + method svæði.',
      },
      {
        id: 'ict-unemployment',
        title: 'ICT Unemployment (VMST G5)',
        subtitle: 'Fjórði ás — skráð atvinnuleysi í J',
        sourceLabel: 'VMST Talnagögn G5',
        methodNote:
          'Árslok (desember) fjöldi á atvinnuleysisskrá, NACE J — Upplýsingar og fjarskipti. Mars 2026 er síðasta mæling.',
        caveat:
          'VMST-flokkun er ekki formlegt ÍSAT — J er þó 1:1 samsvörun. Höfðatölur eingöngu, ekkert hlutfall.',
        state: 'verified',
      },
      {
        id: 'ict-caveat',
        title: 'Interpretation Caveat Panel',
        subtitle: 'Pattern, not proof',
        sourceLabel: 'EPISTEMIC_CLAIMS.md',
        methodNote: 'Skýr aðgreining milli mynsturs og orsakar.',
        caveat: 'Final conclusion háð viðbótarmælingum.',
        state: 'contested',
      },
    ],
    missingDataNote:
      'Vantar samstæðar tekjutölur 2025 fyrir J62 til að loka baseline ágreiningi. VMST-atvinnuleysi (G5) staðfestir fjórða ásinn: +97,5% frá jan 2023 til mars 2026.',
  },
  {
    id: 'knowledge-occupation-collapse',
    label: 'Knowledge Occupation Collapse',
    heading: 'Knowledge Occupation Collapse',
    subheading: 'ISCO samsetningarbreyting 2024 -> 2025',
    briefingSummary:
      'Síðan sýnir nettófækkun í þekkingarstörfum samhliða fjölgun í þjónustu/líkamlegum störfum.',
    riskSignal:
      'Skills policy can drift if composition shifts are not tracked.',
    confidence: 'high',
    freshness: 'Apr 2026',
    evidenceLevel: 'confirmed',
    claims: [
      {
        id: 'isco-net-shift',
        claim:
          '9.300 störf tapast í ISCO 1-4 á meðan 6.900 bætast í ISCO 5-9.',
        level: 'confirmed',
        state: 'verified',
        sourceLabel: 'VIN01100',
        methodNote: 'Ár-við-ár samanburður 2024 vs 2025.',
        caveat: 'Lýsir samsetningu, ekki orsök.',
        lastVerified: '2026-04-11',
      },
    ],
    modules: [
      {
        id: 'isco-ranked-table',
        title: 'Ranked Occupation Change Table',
        subtitle: 'Flokkar 1-9 með nettóbreytingu',
        sourceLabel: 'VIN01100',
        methodNote: 'Hlutfall + absolút breyting birt saman.',
        caveat: 'Stéttaflokkun er lýsandi, ekki orsakasértæk.',
        state: 'verified',
        includesChart: true,
        chartKind: 'ranked-table',
        chartUsageIntent: 'Samanburður á breytingu milli starfaflokka.',
        chartFallbackNote: 'Ranked table placeholder með annotation reit.',
      },
      {
        id: 'isco-slope',
        title: '2024 -> 2025 Shift View',
        subtitle: 'Comparison skeleton for occupation migration',
        sourceLabel: 'VIN01100',
        methodNote: 'Slope/bars fyrir hraða sjónræna túlkun.',
        caveat: 'Placeholder frame þar til data wiring er klárt.',
        state: 'provisional',
        includesChart: true,
        chartKind: 'waterfall',
        chartUsageIntent: 'Sýna hvernig nettóbreyting byggist upp milli flokka.',
        chartFallbackNote: 'Waterfall frame án reiknaðra gilda.',
      },
      {
        id: 'isco-method',
        title: 'Method and Limits',
        subtitle: 'What this chart can and cannot say',
        sourceLabel: 'EPISTEMIC_CLAIMS.md',
        methodNote: 'Skýrir mörk túlkunar.',
        caveat: 'AI orsakatúlkun ekki staðfest.',
        state: 'contested',
      },
    ],
    missingDataNote:
      'Vantar tengd stjórnsýslugögn til að rekja einstaklinga milli geira og ástæðubreyta.',
  },
  {
    id: 'iceland-flying-blind',
    label: 'Iceland Flying Blind',
    heading: 'Iceland Flying Blind',
    subheading: 'Mælingarsamanburður við önnur Norðurlönd',
    briefingSummary:
      'Síðan sýnir að lykilmælingar um AI og vinnumarkað eru ekki til staðar í íslensku kerfi.',
    riskSignal:
      'Without measurement infrastructure, risk response becomes speculative.',
    confidence: 'high',
    freshness: 'Apr 2026',
    evidenceLevel: 'confirmed',
    claims: [
      {
        id: 'flying-blind-core',
        claim:
          'Ísland er utan lykilmælinga sem öll hin Norðurlöndin nota.',
        level: 'confirmed',
        state: 'missing',
        sourceLabel: 'AGENCY_MAP.md + Eurostat + EWCS',
        methodNote: 'Samanburðarmatrix yfir mælingarinnviði.',
        caveat: 'Ástæða fjarveru er ekki fullskýrt staðfest.',
        lastVerified: '2026-04-11',
      },
    ],
    modules: [
      {
        id: 'nordic-matrix',
        title: 'Nordic Measurement Matrix',
        subtitle: 'isoc_eb_ai, EWCS, linked admin data',
        sourceLabel: 'AGENCY_MAP.md',
        methodNote: 'Dimensional coverage mapping.',
        caveat: 'Mismatch getur stafað af governance forgangsröðun.',
        state: 'missing',
        includesChart: true,
        chartKind: 'radar',
        chartUsageIntent: 'Samanburður vídda milli landa.',
        chartFallbackNote: 'Radar skeleton sem undirstrikar coverage eyður.',
      },
      {
        id: 'gap-heatmap',
        title: 'Coverage Heatmap',
        subtitle: 'Where Iceland has no instrument',
        sourceLabel: 'AGENCY_MAP.md',
        methodNote: 'Binary coverage model by measurement type.',
        caveat: 'Heatmap sýnir fjarvist, ekki áhrifastærð.',
        state: 'missing',
        includesChart: true,
        chartKind: 'heatmap',
        chartUsageIntent: 'Sýna binary coverage yfir mælingarvíddir.',
        chartFallbackNote: 'Heatmap grid placeholder með state litaflokkum.',
      },
      {
        id: 'agency-accountability',
        title: 'Responsible Agency Map',
        subtitle: 'Hvaða stofnun á að mæla hvað',
        sourceLabel: 'AGENCY_MAP.md',
        methodNote: 'Agency mapping fyrir accountability.',
        caveat: 'Some governance ownership overlaps.',
        state: 'provisional',
      },
    ],
    missingDataNote:
      'Vantar þátttöku í isoc_eb_ai og EWCS, auk linked admin gagnainnviða fyrir orsakagreiningu.',
  },
  {
    id: 'institutional-silence',
    label: 'Institutional Silence',
    heading: 'Institutional Silence',
    subheading: 'Samráð, þátttaka og stofnanasvar',
    briefingSummary:
      'Síðan sýnir þátttökumynstur í samráðsgögnum og hvað hefur ekki verið staðfest að fullu.',
    riskSignal:
      'Low institutional response capacity increases transition fragility.',
    confidence: 'medium',
    freshness: 'Apr 2026',
    evidenceLevel: 'strong-inference',
    claims: [
      {
        id: 'silence-core',
        claim:
          'Engin stór stéttarfélög sendu umsagnir í lykilsamráði um AI-stefnu.',
        level: 'strong-inference',
        state: 'provisional',
        sourceLabel: 'samradsgatt + MEMO_EMBATTISMANN.md',
        methodNote: 'Yfirferð skráðra umsagna í samráðsgátt.',
        caveat: 'ASÍ þinggögn ekki fulllesin í heild.',
        lastVerified: '2026-04-11',
      },
    ],
    modules: [
      {
        id: 'participation-table',
        title: 'Consultation Participation Table',
        subtitle: 'Stakeholder response map',
        sourceLabel: 'Samráðsgátt S-226',
        methodNote: 'Mappað eftir stofnanafjölskyldum.',
        caveat: 'Aukaskjöl geta breytt túlkun.',
        state: 'provisional',
      },
      {
        id: 'timeline-response',
        title: 'Policy vs Response Timeline',
        subtitle: 'Event and response cadence',
        sourceLabel: 'MEMO_EMBATTISMANN.md',
        methodNote: 'Timeline skeleton með confidence tags.',
        caveat: 'Some event timestamps pending normalization.',
        state: 'stale',
        includesChart: true,
        chartKind: 'timeline',
        chartUsageIntent: 'Setja atburði og viðbrögð í tímaröð.',
        chartFallbackNote: 'Timeline placeholder sem styður confidence merkingar.',
      },
      {
        id: 'unverified-zone',
        title: 'What Remains Unverified',
        subtitle: 'Explicit uncertainty section',
        sourceLabel: 'EPISTEMIC_CLAIMS.md',
        methodNote: 'Sýnir hvað getur hrekkt claim.',
        caveat: 'Needs full ASÍ congress PDF review.',
        state: 'contested',
      },
    ],
    missingDataNote:
      'Vantar fulla handvirka yfirferð á öllum ASÍ-ályktunarskjölum frá 46. þingi.',
  },
  {
    id: 'adversarial-review',
    label: 'Adversarial Review',
    heading: 'Adversarial Review',
    subheading: 'Sterk mótrök, hrekjanleiki og næstu próf',
    briefingSummary:
      'Síðan setur mótrök fram á heiðarlegan hátt og sýnir hvaða gögn gætu breytt niðurstöðu.',
    riskSignal:
      'Ignoring strong counterarguments weakens policy credibility.',
    confidence: 'medium',
    freshness: 'Apr 2026',
    evidenceLevel: 'strong-inference',
    claims: [
      {
        id: 'adversarial-discipline',
        claim:
          'Sterk mótrök eru skráð og metin með sömu gæðakröfum og meginniðurstöður.',
        level: 'strong-inference',
        state: 'contested',
        sourceLabel: 'evidence/07-adversarial-oracle.md',
        methodNote: 'Mótrök flokkuð eftir styrk og hrekjanleika.',
        caveat: 'Ný gögn geta hliðrað ranking.',
        lastVerified: '2026-04-11',
      },
    ],
    modules: [
      {
        id: 'counterargument-register',
        title: 'Counterargument Register',
        subtitle: 'Luddite, small economy, net-positive scenarios',
        sourceLabel: 'evidence/07-adversarial-oracle.md',
        methodNote: 'Strength ranking with response notes.',
        caveat: 'Register is live and should evolve.',
        state: 'contested',
      },
      {
        id: 'falsifier-matrix',
        title: 'Claim vs Falsifier Matrix',
        subtitle: 'What would weaken or reverse each conclusion',
        sourceLabel: 'EPISTEMIC_CLAIMS.md',
        methodNote: 'Maps each claim to potential disconfirming data.',
        caveat: 'Some falsifiers depend on unavailable infrastructure.',
        state: 'missing',
        includesChart: true,
        chartKind: 'ranked-table',
        chartUsageIntent: 'Mappa hvaða gögn gætu hnekkt niðurstöðum.',
        chartFallbackNote: 'Falsifier matrix placeholder með method zone.',
      },
      {
        id: 'conclusion-toggle',
        title: 'Current vs If-Falsified',
        subtitle: 'Scenario toggle placeholder',
        sourceLabel: 'dashboard-spec.md',
        methodNote: 'UI skeleton for adversarial scenario view.',
        caveat: 'Scenario engine not yet data-wired.',
        state: 'provisional',
        includesComparisonToggle: true,
      },
    ],
    missingDataNote:
      'Mikilvæg falsifier gögn eru háð mælingum sem eru ekki til í núverandi innviðum.',
  },
]
